name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  call-pre-commit:
    name: Pre-commit Checks
    uses: ./.github/workflows/pre-commit.yml

  call-tests:
    name: Tests
    needs: call-pre-commit
    uses: ./.github/workflows/test.yml

  call-security:
    name: Security Scan
    needs: call-tests
    uses: ./.github/workflows/security.yml
