name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: "3.12"

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Set up virtual env
      run: uv venv --python ${{ env.PYTHON_VERSION }}

    - name: Activate virtual env
      run: source .venv/bin/activate

    - name: Install dependencies
      run: |
        uv pip install -e ".[dev]"

    - name: Run tests with coverage
      run: |
        uv run pytest --cov=template_mcp_server --cov-report=xml --cov-report=term-missing --cov-fail-under=50

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
